import type { CrmState } from "./types";

const now = () => new Date().toISOString();
const daysFromNow = (n: number) =>
  new Date(Date.now() + n * 24 * 60 * 60 * 1000).toISOString();

export function buildSeed(): CrmState {
  const companies = [
    {
      id: "c1",
      name: "Atelier Martin",
      industry: "Automobile",
      website: "https://atelier-martin.fr",
      phone: "+33 1 23 45 67 89",
      address: "12 rue des Forges, 75011 Paris",
      notes: "Client historique, volume régulier.",
      createdAt: now(),
    },
    {
      id: "c2",
      name: "Transports Dubois",
      industry: "Logistique",
      website: "https://dubois-transports.fr",
      phone: "+33 4 78 12 34 56",
      address: "45 avenue du Rhône, 69003 Lyon",
      notes: "Flotte de 35 véhicules.",
      createdAt: now(),
    },
    {
      id: "c3",
      name: "Garage Leroy & Fils",
      industry: "Automobile",
      website: "https://garage-leroy.fr",
      phone: "+33 2 40 11 22 33",
      address: "8 boulevard de la Liberté, 44000 Nantes",
      notes: "Intéressé par l'offre pro premium.",
      createdAt: now(),
    },
  ];

  const contacts = [
    {
      id: "p1",
      firstName: "Sophie",
      lastName: "Martin",
      email: "sophie.martin@atelier-martin.fr",
      phone: "+33 6 12 34 56 78",
      position: "Directrice",
      companyId: "c1",
      tags: ["VIP", "Fidèle"],
      notes: "Préfère être contactée le matin.",
      createdAt: now(),
    },
    {
      id: "p2",
      firstName: "Julien",
      lastName: "Dubois",
      email: "j.dubois@dubois-transports.fr",
      phone: "+33 6 45 67 89 01",
      position: "Responsable achats",
      companyId: "c2",
      tags: ["Prospect chaud"],
      notes: "Renouvelle sa flotte au T3.",
      createdAt: now(),
    },
    {
      id: "p3",
      firstName: "Camille",
      lastName: "Leroy",
      email: "camille@garage-leroy.fr",
      phone: "+33 6 78 90 12 34",
      position: "Gérant",
      companyId: "c3",
      tags: ["Nouveau"],
      notes: "Demandé une démo.",
      createdAt: now(),
    },
  ];

  const deals = [
    {
      id: "d1",
      title: "Pack Pro - Atelier Martin",
      amount: 12500,
      currency: "EUR" as const,
      stage: "negociation" as const,
      contactId: "p1",
      companyId: "c1",
      probability: 75,
      closeDate: daysFromNow(14),
      notes: "Attente validation finale du devis.",
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "d2",
      title: "Renouvellement flotte Dubois",
      amount: 48000,
      currency: "EUR" as const,
      stage: "proposition" as const,
      contactId: "p2",
      companyId: "c2",
      probability: 50,
      closeDate: daysFromNow(45),
      notes: "Devis envoyé, relance prévue vendredi.",
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "d3",
      title: "Démo - Garage Leroy",
      amount: 3200,
      currency: "EUR" as const,
      stage: "qualifie" as const,
      contactId: "p3",
      companyId: "c3",
      probability: 30,
      closeDate: daysFromNow(30),
      notes: "Démo programmée la semaine prochaine.",
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "d4",
      title: "Contrat entretien annuel",
      amount: 7800,
      currency: "EUR" as const,
      stage: "gagne" as const,
      contactId: "p1",
      companyId: "c1",
      probability: 100,
      closeDate: daysFromNow(-3),
      notes: "Signé le mois dernier.",
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "d5",
      title: "Opportunité pilote",
      amount: 2100,
      currency: "EUR" as const,
      stage: "nouveau" as const,
      probability: 10,
      closeDate: daysFromNow(60),
      notes: "Lead reçu via formulaire.",
      createdAt: now(),
      updatedAt: now(),
    },
  ];

  const tasks = [
    {
      id: "t1",
      title: "Rappeler Sophie Martin",
      description: "Valider les derniers points du devis.",
      status: "a_faire" as const,
      priority: "haute" as const,
      dueDate: daysFromNow(1),
      contactId: "p1",
      dealId: "d1",
      createdAt: now(),
    },
    {
      id: "t2",
      title: "Envoyer proposition à Dubois",
      description: "Préparer le pack logistique 35 véhicules.",
      status: "en_cours" as const,
      priority: "haute" as const,
      dueDate: daysFromNow(3),
      contactId: "p2",
      dealId: "d2",
      createdAt: now(),
    },
    {
      id: "t3",
      title: "Préparer la démo Leroy",
      description: "Slide deck + chiffres clés.",
      status: "a_faire" as const,
      priority: "moyenne" as const,
      dueDate: daysFromNow(5),
      contactId: "p3",
      dealId: "d3",
      createdAt: now(),
    },
    {
      id: "t4",
      title: "Classer les factures du mois",
      status: "termine" as const,
      priority: "basse" as const,
      dueDate: daysFromNow(-2),
      createdAt: now(),
    },
  ];

  return { companies, contacts, deals, tasks };
}
